-- Merge reindexed matches generated by `reindex_skt.sql` into `lex_master` and `lex_senses`

-- lex_master column updates (also in `lex_master_column_updates.sql)
ALTER TABLE lex_master ADD COLUMN related INT DEFAULT NULL, ALGORITHM=INPLACE, LOCK=NONE;
-- Alternatively, try:
-- ALTER TABLE lex_master ADD COLUMN related INT DEFAULT NULL, ALGORITHM=INSTANT;
ALTER TABLE lex_master MODIFY COLUMN gender VARCHAR(64), ALGORITHM=INPLACE;

-- Check ID matching
SELECT r.word_id, r.reflex, r.gloss_eng, m.lemma_id, m.lemma_translit, m.gloss
FROM lex_ref_link r
LEFT JOIN temp_skt_reindexed_main m
ON r.lang = 'Skt.'
AND word_id = lemma_id;

-- Get lex_ref_link entries matched to demoted entries
SELECT r.* FROM lex_ref_link r
LEFT JOIN temp_skt_reindexed_main m
ON r.lang = 'Skt.'
AND word_id = lemma_id
WHERE r.lang = 'Skt.' 
AND word_id IS NOT NULL
AND lemma_id IS NULL;

DROP TABLE IF EXISTS temp_skt_demotions;
CREATE TABLE temp_skt_demotions (
	lex_ref_link_id INT NOT NULL,
    orig_word_id INT NOT NULL,
    reflex VARCHAR(255),
    gloss_eng TEXT,
    master_lemma VARCHAR(255),
    master_entry_str MEDIUMTEXT,
    new_word_id INT
);
INSERT INTO temp_skt_demotions
SELECT r.lex_ref_link_id, r.word_id, r.reflex, r.gloss_eng, m.lemma, m.entry_str, NULL
FROM lex_ref_link r
LEFT JOIN temp_skt_reindexed_main t
ON r.lang = t.lang
AND word_id = t.lemma_id
LEFT JOIN lex_master m
ON r.lang = m.lang
AND r.word_id = m.lemma_id
WHERE r.lang = 'Skt.' 
AND word_id IS NOT NULL
AND t.lemma_id IS NULL;

SELECT * FROM temp_skt_demotions;

-- Remediate entries -- see `skt-lex-ref-link-demotions` (.csv or .xlsx)
-- `new_word_id` with asterisk indicates change in `temp_skt_reindexed_main`
-- Without asterisk indicates change in `lex_ref_link` (IMPORTANT!)
-- SELECT lang, lemma_id, lemma_translit, sense_num, orthography, etymology, entry_str FROM temp_skt_reindexed_main WHERE lemma_translit = 'heman';
-- SELECT * FROM lex_master WHERE lemma_id = 300329;
-- SELECT s.* FROM temp_skt_reindexed_senses s JOIN temp_skt_reindexed_main m ON s.lemma_id = m.lemma_id WHERE lemma_translit = 'a';
-- SELECT * FROM temp_skt_reindexed_senses WHERE lemma_id IN (200571);
-- SELECT * FROM temp_skt_reindexed_main WHERE lemma_id = 119573;

-- Update `lex_ref_link`
-- SELECT lang, lex_ref_link_id, word_id, reflex, gloss_eng
-- FROM lex_ref_link 
-- WHERE word_id = 301310;
-- UPDATE lex_ref_link 
-- SET word_id = 202226     -- NEW WORD_ID
-- WHERE word_id = 301310; -- OLD WORD_ID
-- -- AND lang = 'Skt.';

-- Import fixed reindexed files
TRUNCATE TABLE temp_skt_reindexed_main;
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/skt_reindexed_main.csv'
INTO TABLE temp_skt_reindexed_main
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SELECT * FROM temp_skt_reindexed_main;