---
title: "Meeting Notes"
format: html
editor: visual
---

## 8/26 Notes

-   Tasked w/ figuring out how to tokenize & lemmatize Latin texts

    -   Pretty much everything is pointing to CLTK

    -   Version problems, 3.12 is working though

-   Task for next time:

    -   How feasible is it to pre-process the data?

    -   What are all of the categories that are spit out through the lemmatization?

        -   What do they mean?

    -   Can we create one massive spreadsheet, organized by text

    -   Add category if not there: genre (prose, poetry), date_composed

    -   For values that = 'None', can we fill those values?

## 9/2 Notes

-   Jacob did a bunch of exploration w/ word features

-   Lexicon process is really time-consuming (it takes 100x longer)

    -   Can we create a list of lemmas with corresponding based off of Lewis & Short

-   Processes to figure out / create – phonology, morphology, prosody

-   Can we open up the hood of Lewis Short? How would this lexicon be best organized?

-   Game plan:

    -   Lewis & Short dictionary:

        -   Convert yaml file to csv / excel

        -   Figure out all of the columns

        -   meaning, line illustrating meaning

        -   

## 9/9 Notes

-   Parsing XML file, we've got lexicon built!

-   Separate different meanings by ";"

## 9/16 Notes

-   Next task: do we need to do JSON? If we switch to CSV, what information *must* we lose?

-   Io will give Jacob access to DB, he can poke around

## 9/23 Notes

-   Looking at formats for the lexicon

-   Easiest to store as csv, with xml tags

-   Etymology - first word is the actual source, prefix / cmpd boundaries indicated; for linking to other lemmas first see if there's a standalone lemma that matches (e.g. ab-igo \> abigo) or if not (ab-ante), link to separate lemmas

-   Next time – can we connect the dictionary w/ the texts?

-   Parsing Livy's History, book 1:

    -   1 file: the complete txt, in txt format

    -   1 file: csv, with columns: index, token, lemma, pos, features, pronunciation (?)

-   How long does it take to parse the book?

-   How much space does this take up?

    -   How about the text file?

## 9/30

-   Nothing crazy for this week

-   Rest of L&S parsed, hasn't been reviewed completely, Jacob fixing as he finds issues

    -   69.7 meg

-   First book of Livy parsed - 24000 tokens, going to have millions of tokens

    -   3.5 meg

-   Task for next week –

    -   download lex_ref_link

    -   identify all of the "lat." forms (look for the lat string)

    -   try to match all of these reflexes with a lemma in L&S

-   <https://drawsql.app/teams/derbi-pie/diagrams/derbi-pie-db-structure>

## 10/7

-   Keep trucking on both tasks: (1) linking lex_ref_link to lex_master; (2) parse more of the corpus

-   Andrew to try to build Greek lexicon in same format as Lewis Short

    -   look in Tesserae Project - can we parse Greek projects?

-   Corpus - Tesserae Project

## 10/14

-   Jacob - refining connections between lex_ref and lewis-short

    -   5400 Latin entries

    -   1000 unmatched - Jacob going to run through CLTK to generate lemma

    -   Jacob to prototype a Latin word entry lookup

-   Andrew - has started working on Sanskrit, not yet figured out how to convert gk mdx to xml/csv

    -   sort skt.csv in the style of Latin

    -   use matchreflexdefinition.sql to try to line up words with what's in lex_ref_line

## 10/21

-   To talk about:

-   Jacob:

    -   filling in gaps in lex_ref_link, got about 226 more that matched

        -   CLTK didn't lemmatize as well as hoped – perhaps stanza relies on context?

        -   going to send list of remaining words for me to match

        -   match the reflex to the lemma (column 1)

    -   has been parsing more of the corpus; he's written a script to take a path from Tesserae to parse automatically

-   To do:

    -   Andrew will try to match remaining words

    -   Jacob will:

        -   break Latin senses into different rows

        -   create column called "subentry" or something like that, link up to base entry

        -   link Sanskrit words to lex_ref_link?

        -   csv for Andrew to check:

            -   reflex, german_meaning, lewis-short lemma, lewis-short gloss

## 10/29

-   Jacob will:

    -   Send Andrew an updated version of the matched words, with the German gloss for easier matching

    -   Begin piloting the website for the word search

-   Andrew will:

    -   Complete matching the unmatched words

    -   Look through the matched word list for any errors

## 11/4

-   Andrew finished w/ null matches

-   Jacob will edit reflex_lemma_table so that sense_1 and sense_2 columns will replace entry

-   To do:

    -   Create a "sense_index" column

    -   Going to figure out the best way to organize the data (two tables, one?)

    -   Needs to run through CLTK for phonetic transcriptions

        -   How to deal with missing entries?

## 11/11

-   Has been done:

    -   Andrew confirmed 1100 or so lemma matches with help of GPT
    -   lex_master
    -   sense_master
    -   Jacob has:
        -   query working for lexicon

-   To do:

    -   Jacob will:
        -   take out matched = 1 from excel file
            -   add another column with "all_senses" for those with 0
            -   Andrew will use GPT and own brain to match remaining
        -   Send structure of lex_master & sense_master for Arnav (Sanskrit dictionary)
        -   Work on populating data on frontend for query

## 11/18

-   Jacob did work in derbi-pie-web mostly

    -   for the most part getting the front end data to populate

-   To share with Arnav:

    -   lewis-short-template.xslt

    -   put in xml entry

    -   show SQL file

-   For next time:

    -   for variants (like Lucina), add a link to the base word that it's a variant of

    -   try to work in etymology information from NIL, LIV, Pokorny

    -   look at query mock-ups

## 12/2

-   Final Tasks for Jacob:

    -   Embed Livy & Aeneid data under "Attestations"

        -   Organize by form?

    -   Create readme/instructions doc for future work
